export const ACTIONS = Object.freeze({
  // Auth
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SIGNUP: "SIGNUP",
  RESET_PASSWORD: "RESET_PASSWORD",
  UPDATE_PASSWORD:"UPDATE_PASSWORD",

  // Appointments
  BOOK_APPOINTMENT: "BOOK_APPOINTMENT",
  CANCEL_APPOINTMENT: "CANCEL_APPOINTMENT",
  COMPLETE_APPOINTMENT: "COMPLETE_APPOINTMENT",
  CHANGE_APPOINTMENT_STATUS:"CHANGE_APPOINTMENT_STATUS",
  // Medical
  CREATE_PRESCRIPTION: "CREATE_PRESCRIPTION",
  CREATE_MEDICAL_REPORT: "CREATE_MEDICAL_REPORT",

  // Admin actions
  CREATE_DOCTOR: "CREATE_DOCTOR",
  UPDATE_DOCTOR_PROFILE:"UPDATE_DOCTOR_PROFILE",
  MAKE_DOCTOR_UNACTIVE: "MAKE_DOCTOR_UNACTIVE",
  CREATE_RECEPTIONIST: "CREATE_RECEPTIONIST",
  UPDATE_RECEPTIONIST_PROFILE:"UPDATE_RECEPTIONIST_PROFILE",
  DELETE_RECEPTIONIST: "DELETE_RECEPTIONIST",
  CHANGE_PATIENT_STATUS: "CHANGE_PATIENT_STATUS",
  MAKE_PATIENTS_UNACTIVE:"MAKE_PATIENTS_UNACTIVE",
  MAKE_RECEPTIONIST_UNACTIVE:"MAKE_RECEPTIONIST_UNACTIVE",
  // Profile
  UPDATE_PROFILE: "UPDATE_PROFILE",
  COMPLETE_PATIENT_PROFILE:"COMPLETE_PATIENT_PROFILE",

  // Patient
  CREATE_PATIENT_USER:"CREATE_PATIENT_USER",

  // Clinic
  UPDATE_CLINIC_INFORMATION:"UPDATE_CLINIC_INFORMATION",
  UPDATE_CLINIC_SCHEDULE:"UPDATE_CLINIC_SCHEDULE",
  CREATE_REVIEW:"CREATE_REVIEW",
  DELETE_REVIEW:"DELETE_REVIEW",
  
  CREATE_SPECIALIZATION:"CREATE_SPECIALIZATION",
  ADD_SPECIALIZATION:"ADD_SPECIALIZATION",
  DELETE_SPECIALIZATION:"DELETE_SPECIALIZATION",
  UPDATE_SPECIALIZATION:"UPDATE_SPECIALIZATION",
});